language: ruby
bundler_args: -j4 --without development --deployment --path=${BUNDLE_PATH:-vendor/bundle}
cache:
  directories:
    - vendor/bundle
services:
  - elasticsearch
  - redis
before_install:
  - "sh -e /etc/init.d/xvfb start"
before_script:
  - cp config/database.sample.yml config/database.yml
  - cp config/settings.sample.yml config/settings.yml
  - "echo '-r power_assert --color --format d' > .rspec"
  - wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | sudo apt-key add -
  - sudo sh -c 'echo "deb http://dl.google.com/linux/chrome/deb/ stable main" >> /etc/apt/sources.list.d/google.list'
  - sudo apt-get update
  - sudo apt-get install google-chrome-stable
  - wget -O chromedriver.zip http://chromedriver.storage.googleapis.com/2.11/chromedriver_linux64.zip
  - sudo unzip chromedriver.zip chromedriver -d /usr/local/bin/
  - sudo chmod +x /usr/local/bin/chromedriver
script: bundle exec rake db:create db:migrate spec
rvm:
  - 2.1
  - 2.2
env:
  global:
    - CI=true
    - DISPLAY=:99.0
notifications:
  email:
    on_success: change
