language: ruby
cache: bundler
services:
  - elasticsearch
  - redis
before_script:
  - cp config/database.sample.yml config/database.yml
  - cp config/settings.sample.yml config/settings.yml
  - cp config/resque.sample.yml config/resque.yml
  - bundle exec rake db:create
  - bundle exec rake db:migrate
  - "echo '--color --format d' > .rspec"
script: bundle exec rspec spec
rvm:
  - 2.1.0
env:
  global:
    - CI=true
notifications:
  email:
    on_success: change
