language: ruby
cache: bundler
before_script:
  - cp config/database.sample.yml config/database.yml
  - cp config/settings.sample.yml config/settings.yml
  - cp config/resque.sample.yml config/resque.yml
  - bundle exec rake db:create
  - bundle exec rake db:migrate
  - "echo '--color' > .rspec"
script: bundle exec rake spec
rvm:
  - 2.1.0
notifications:
  email:
    on_success: change
