language: ruby
before_script:
  - "cp config/database.sample.yml config/database.yml"
  - sudo ci/install_phantomjs
  - "export PATH=phantomjs/bin:$PATH"
  - phantomjs --version
  - bundle exec rake db:create
  - bundle exec rake db:migrate
script: "bundle exec rake spec"
rvm:
  - 2.0.0
notifications:
  email:
    on_success: never
