language: ruby
before_install:
  - phantomjs --version
before_script:
  - cp config/database.sample.yml config/database.yml
  - cp config/settings.sample.yml config/settings.yml
  - cp config/resque.sample.yml config/resque.yml
  - bundle exec rake db:create
  - bundle exec rake db:migrate
  - "echo '--color' > .rspec"
script: bundle exec rake spec
rvm:
  - 2.0.0
notifications:
  email:
    on_success: never
