#!/bin/bash

[ ! -s contrib ] && mkdir contrib
version=1.0.1
curl -O "https://download.elasticsearch.org/elasticsearch/elasticsearch/elasticsearch-${version}.tar.gz"
tar xzf elasticsearch-${version}.tar.gz
mv elasticsearch-${version} contrib/elasticsearch/
rm elasticsearch-${version}.tar.gz
