defaults: &default
  aws_access_key_id: "AWS KEY"
  aws_secret_access_key: "AWS SECRET KEY"
  aws_region: "ap-northeast-1"
  fog_directory: "dir"
  carrierwave_storage: "fog"
  download_dir: <%= (Rails.root + "public/videos").to_s %>

development:
  <<: *default

test:
  <<: *default

production:
  <<: *default
