defaults: &default
  twitter_consumer_key: "TWITTER CONSUMER KEY"
  twitter_consumer_secret: "TWITTER CONSUMER SECRET"
  aws_access_key_id: "AWS KEY"
  aws_secret_access_key: "AWS SECRET KEY"
  aws_region: "ap-northeast-1"
  fog_directory: "dir"
  download_dir: <%= (Rails.root + "public/videos").to_s %>

development:
  carrierwave_storage: "fog"
  <<: *default

test:
  carrierwave_storage: "file"
  <<: *default

production:
  carrierwave_storage: "fog"
  <<: *default
