defaults: &default
  twitter_consumer_key: <%= ENV["TWITTER_CONSUMER_KEY"] %>
  twitter_consumer_secret: <%= ENV["TWITTER_CONSUMER_SECRET"] %>
  facebook_consumer_key: <%= ENV["FACEBOOK_CONSUMER_KEY"] %>
  facebook_consumer_secret: <%= ENV["FACEBOOK_CONSUMER_SECRET"] %>
  aws_access_key_id: <%= ENV["AWS_KEY"] || "dummy" %>
  aws_secret_access_key: <%= ENV["AWS_SECRET_KEY"] || "dummy" %>
  aws_region: <%= ENV.fetch("AWS_REGION", "ap-northeast-1") %>
  fog_directory: "dir"
  download_dir: <%= ENV["DOWNLOAD_DIR"] || (Rails.root + "public/videos").to_s %>
  stop_tag_words:
    - ニコニコカラオケDB
    - ニコニコカラオケＤＢ
    - VOCALOID
    - Vocaloid
    - ボカロカラオケDB
    - ボカロカラオケＤＢ
    - ニコカラ
    - vocaloid
    - 音楽
    - ﾆｺﾆｺカラオケDB
    - カラオケ
    - JOYSOUND配信中
    - 歌ってみた
    - 演奏してみた
    - OffVocal
    - offvocal
    - OFFvocal
    - ジェバンニ

development:
  carrierwave_storage: "fog"
  <<: *default

test:
  carrierwave_storage: "file"
  <<: *default

production:
  carrierwave_storage: "fog"
  <<: *default
