#!/bin/bash

if [ "${FFMPEG_VERSION}" = "" ]; then
  version=ffmpeg-1.1.3
else
  version=ffmpeg-${FFMPEG_VERSION}
fi
wget http://www.ffmpeg.org/releases/$version.tar.bz2
tar xjf $version.tar.bz2
mv $version ffmpeg_src
mkdir ffmpeg
current=`pwd`
cd ffmpeg_src
./configure --prefix=$current/ffmpeg --enable-pthreads --enable-gpl --enable-version3 --enable-nonfree --enable-libx264 --enable-libvpx --enable-libfaac --enable-libvorbis --enable-libtheora
make && make install
