#!/bin/bash

solr_version=4.1.0
curl -C -o solr-${solr_version}.tgz --speed-time 20 --speed-limit 10240 --retry 10 "http://archive.apache.org/dist/lucene/solr/${solr_version}/solr-${solr_version}.tgz"
tar xzf solr-${solr_version}.tgz
mkdir contrib
mv solr-${solr_version} contrib/solr/
rm solr-${solr_version}.tgz

# How to Run solr
# bundle exec rake sunspot:solr:start
# Or
# bundle exec rake sunspot:solr:run
